service: sls-punkapi-bot

provider:
  name: aws
  runtime: ruby2.5
  region: eu-west-1
  stackTags:
    author: "rajraj"

functions:
  punkapi:
    handler: punkapi.handler
    events:
      - http: GET /punkapi
